---
Name: foundationforms
---
SilverStripe\Forms\FieldList:
  extensions:
    - Foundation\Extensions\FoundationFieldListExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: Foundation\Forms\FoundationMemberLoginForm
---
Only:
  moduleexists: userforms
---
SilverStripe\UserForms\Form\UserForm:
  extensions:
    - Foundation\Extensions\FoundationUserFormExtension
---
Only:
  moduleexists: comments
---
CommentingController:
  extensions:
    - Foundation\Extensions\FoundationCommentingController
